### ISSUE TITLE
Lua typechecker

### ISSUE THREAD

**Issue by Perryvw** [tangzx/IntelliJ-EmmyLua#53]
Type checkers are a great tool to improve robustness of code written. It would be great to add some kind of type-checking capabilities to EmmyLua where the types of arguments are matched with the expected types as defined in their definition. This would also include checking if returned values match the specified return types.

This could be a plugin setting that could be enabled or not, and when enabled shows either an error or a warning whenever a type missmatch occurs, and would require the types of each function to be declared. I envision this working similar to TypeScript's type system.

For example:
```
--- @type myEnum
ENUM_VAL = 1

--- @param enum myEnum
--- @return number
function myFunction(enum)
    return "2" -- ERROR: Return type (string) does not match specified type (number)
end

myFunction(3) -- ERROR: Parameter 1' type (int) does not match expected type (myEnum)
```

I don't know if this is something that is on the agenda or how hard this would be to include in the plugin, but I think including this functionality would be great.

PS: I am more than willing to share my knowledge on the subject if needed.

**Comment by DoctorGester** [comment]
@tangzx 

![](http://dg-lab.com/towed)

![](http://dg-lab.com/towen)

Has a ton of issues rn such as some things evaluating as TyLazyClass and nil evaluating as any. Also argument number checking is a bad idea since a lot of functions even in standard lib have optional args :(

Argument number could still be enforced with some function flag

**Comment by tangzx** [comment]
@DoctorGester Lua is so flexible that it's hard to implement this featrue.
Note that the `optional` keyword is obsolete since `1.1.9`. Use `@overload` instead, see [changelogs#1.1.9](https://tangzx.github.io/emmydoc/changelogs/1.1.9.html)

So we match arguments with `mainSignature` and overload signatures :(

 `ITy` should be add fun like
```kotlin
func ITy.canUnifyWith(other:ITy):Boolean
```
Then check argument type:
```kotlin
if (!guessedArgumentType.canUnifyWith(signatureParameter.ty) {
    ...
}
```

**Comment by DoctorGester** [comment]
I don’t think I can put @overload on table.insert though?

**Comment by tangzx** [comment]
Ah, what do you mean? std apis are predefined(builtin lua files)
![image](https://user-images.githubusercontent.com/3354360/30847177-1fb33594-a2cd-11e7-8dc9-04b96b62d8bb.png)

**Comment by DoctorGester** [comment]
Yeah usually I just do table.insert(t, value) and since the original function has 3 arguments and no overloads marked it is reported as an error

**Comment by tangzx** [comment]
Yes, that's an issue, really bugging me

**Comment by Perryvw** [comment]
@tangzx I'm working on implementing this with DoctorGester

**Comment by tangzx** [comment]
@Perryvw @DoctorGester 
Wow... awesome! 👍

**Comment by tangzx** [comment]
btw here's a ton of code modifications about optimize bnf. You'd better pull those commits

**Comment by Perryvw** [comment]
When I have an enum value, like:
```
--- @type team_t
TEAM_GOODGUYS = 3
```
Its type is team_t|TEAM_GOODGUYS, instead of team_t as expected, is this intentional or a bug?

**Comment by Perryvw** [comment]
See #59
